---
- name: Update apt
  become: true
  apt:
    update_cache: yes

- name: Install needed packages
  become: true 
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - reprepro
    # - createrepo
