---
# This playbook is used for deploying the production chacra instance that's
# used for creating ceph releases. It does not register or report status
# to shaman.ceph.com.

- hosts: production
  user: ubuntu
  roles:
    - common
    - repos
    - statsd
  vars:
     app_name: "chacra"
     use_ssl: true
     wsgi_file: wsgi.py
     wsgi_callable: application
     ansible_ssh_port: 2222
     binary_root: "/opt/binaries"
     repos_root: "/opt/repos"
     branch: "main"
     development_server: false
     use_letsencrypt: true
     fqdn: "chacra.ceph.com"

     # graphite reporting for statsd
     graphite_host: "shaman.ceph.com"
     # required
     # graphite_api_key: '1234-asdf-1234'

     # required on first deploy
     # api_user: "admin"
     # api_key: "secret"

     # leave blank, we want prod_callbacks.py created, by not used
     callback_user: ""
     callback_key: ""

     nginx_ssl_cert_path: "/etc/letsencrypt/live/{{ fqdn }}/fullchain.pem"
     nginx_ssl_key_path: "/etc/letsencrypt/live/{{ fqdn }}/privkey.pem"
