---

- hosts: all
  user: vagrant
  roles:
    - common
    - repos
    - statsd
  vars:
     app_name: "chacra"
     use_ssl: true
     wsgi_file: wsgi.py
     wsgi_callable: application
     ansible_ssh_port: 22
     restart_app: true
     binary_root: "/opt/binaries"
     repos_root: "/opt/repos"
     branch: "main"
     development_server: true
     short_hostname: "3"
     fqdn: "3.node.a"
     api_user: "admin"
     api_key: "secret"

     # callbacks
     # using an IP here because vagrant won't know about
     # the hostnames of other vagrant machines
     callback_url: "https://192.168.111.116/api/repos/"
     callback_user: "admin"
     callback_key: "secret"
     callback_verify_ssl: False
     graphite_api_key: '1234-asdf-1234'

     health_ping: True
     health_ping_url: "https://192.168.111.116/api/nodes/"

     nginx_ssl_cert_path: "/etc/ssl/certs/{{ fqdn }}-bundled.crt"
     nginx_ssl_key_path: "/etc/ssl/private/{{ fqdn }}.key"
